# Generated by Django 2.1.7 on 2019-03-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pondi', '0002_auto_20190219_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pendingfriends',
            field=models.ManyToManyField(related_name='pending', to='pondi.Profile'),
        ),
    ]
