# Generated by Django 2.1.7 on 2019-03-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pondi', '0003_profile_pendingfriends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foo',
            field=models.CharField(default='bar', max_length=50),
        ),
    ]
