# Generated by Django 2.1.7 on 2019-03-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pondi', '0004_profile_foo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='foo',
        ),
    ]
