# Generated by Django 2.1.5 on 2019-03-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pondi', '0005_auto_20190303_1933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
        migrations.AlterField(
            model_name='profile',
            name='closefriends',
            field=models.ManyToManyField(related_name='close', to='pondi.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pendingfriends',
            field=models.ManyToManyField(to='pondi.Profile'),
        ),
    ]
