# Generated by Django 2.1.7 on 2019-03-09 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pondi', '0006_auto_20190306_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
